name: CD (Déploiement de l'API sur Hugging Face Spaces)

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'dashboard/api/**'
      - 'requirements.txt'
      - 'Dockerfile'

jobs:
  deploy-to-hf-spaces:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true
          
      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Installation de Hugging Face Hub
        run: pip install huggingface_hub
          
      - name: Déploiement via huggingface-cli
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_NAME: "S0l0kame/OpenClassroomP9"
        run: |
          # Téléversement direct du code vers le Space (gère LFS automatiquement et ignore l'historique Git)
          huggingface-cli upload $HF_SPACE_NAME . --repo-type space --token $HF_TOKEN --exclude ".git/*" ".github/*"